apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-pvc
  namespace: ai-services
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
