apiVersion: v1
kind: Namespace
metadata:
  name: ai-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ai-services
spec:
  replicas: 1
  selector:
    matchLabels: { app: ollama }
  template:
    metadata:
      labels: { app: ollama }
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
         # 新增：挂载 PVC 到 Ollama 模型目录
        volumeMounts:
        - name: ollama-model-volume
          mountPath: /root/.ollama
      # 新增：关联 PVC
      volumes:
      - name: ollama-model-volume
        persistentVolumeClaim:
          claimName: ollama-model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ai-services
spec:
  type: NodePort
  selector: { app: ollama }
  ports:
  - port: 11434
    targetPort: 11434
